/* Generated By:JavaCC: Do not edit this line. PxrParserConstants.java */
package com.brentcroft.pxr.parser;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface PxrParserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int LF = 1;
  /** RegularExpression Id. */
  int CR = 2;
  /** RegularExpression Id. */
  int SPACE = 3;
  /** RegularExpression Id. */
  int BANG = 4;
  /** RegularExpression Id. */
  int HASH = 5;
  /** RegularExpression Id. */
  int EQUALS = 6;
  /** RegularExpression Id. */
  int COLON = 7;
  /** RegularExpression Id. */
  int CONT = 8;
  /** RegularExpression Id. */
  int CHAR = 9;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\"\\n\"",
    "\"\\r\"",
    "<SPACE>",
    "<BANG>",
    "<HASH>",
    "\"=\"",
    "\":\"",
    "<CONT>",
    "<CHAR>",
    "\"\\\\\"",
  };

}
